In [1]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['Pune','Pune',np.nan,'Hyd']}
df=pd.DataFrame(Data)
df

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [5]:
pd.read_csv('data_missing.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data_missing.csv'

In [3]:
df.to_csv('data_misssing.csv',index=False)

In [7]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['Pune','Pune',np.nan,'Hyd']}
df1=pd.DataFrame(Data)
df1

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [13]:
df1.to_csv('data_misssing1.csv',index=False)

In [15]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

In [17]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

**isnull**

In [20]:
df.isnull()

Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [22]:
df1.isnull()

Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [24]:
df.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [26]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**fillna**

In [29]:
df.fillna(30) # Not recomended

Names   Age  City
0   Ramesh  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

In [31]:
df1.fillna(30)

Names   Age  City
0   Ramesh  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

- in the above one is we are filling randomly 
- all the columns are fillied with random number
- it is not a good approach because in a data we have different data types

In [34]:
df.fillna('Hyd')

Names   Age  City
0   Ramesh   Hyd  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      Hyd  27.0   Hyd

In [36]:
df1.fillna('Hyd')

Names   Age  City
0   Ramesh   Hyd  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      Hyd  27.0   Hyd

**what is the differenve between np.nan and None**

In [39]:
np.nan+5

nan

In [41]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [43]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])

In [45]:
arr1

array([ 1.,  2., nan,  3.])

In [47]:
arr2

array([1, 2, None, 3], dtype=object)

In [51]:
np.nansum(arr1),np.sum(arr1)

(6.0, nan)

In [53]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

- np.nan represents Float type
- None represents Object type
- if data operations related to Maths then nan format is better

**Fill the value based on column**

In [57]:
#df.fillna()
df['Names'].fillna('Manish')

0     Ramesh
1     Suresh
2    Sathish
3     Manish
Name: Names, dtype: object

In [59]:
df

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [61]:
df['Age'].fillna(20)

0    20.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [65]:
df['Age'].fillna('20')

0      20
1    22.0
2    25.0
3    27.0
Name: Age, dtype: object

In [67]:
df['Age'].fillna('20').values

array(['20', 22.0, 25.0, 27.0], dtype=object)

In [69]:
df['Age'].fillna(20).values

array([20., 22., 25., 27.])

In [ ]:
df['Age'].fillna(20).fillna(20).values
df['Age'].fillna('20').fillna('20').values

In [73]:
df

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [77]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

- becasue of one value total data type is changed
- we can convert one data type column to another data type astype

In [ ]:
df['Age2']=df['Age2'].astype('float')

In [84]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object